# Generated by Django 2.2.4 on 2019-10-09 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='selected_family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='family.Family'),
        ),
    ]
