# Generated by Django 2.2.4 on 2019-10-10 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_remove_profile_theme'),
        ('userprofile', '0002_profile_selected_family'),
    ]

    operations = [
    ]
