# Generated by Django 2.2.4 on 2019-10-07 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mapbox_location_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artefact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('OKY', 'No Problem'), ('LST', 'Lost'), ('DMG', 'Damaged'), ('DST', 'Destroyed')], default='OKY', max_length=9)),
                ('is_public', models.BooleanField(default=False)),
                ('upload', models.FileField(blank=True, default=False, upload_to='')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('location', mapbox_location_field.models.LocationField(map_attrs={}, null=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artefact_administrator_of', to=settings.AUTH_USER_MODEL)),
                ('belongs_to_families', models.ManyToManyField(related_name='has_artefacts', to='family.Family')),
            ],
            options={
                'verbose_name': 'artefact',
                'verbose_name_plural': 'artefacts',
                'ordering': ('-added_at',),
            },
        ),
    ]
