# Generated by Django 2.2.4 on 2019-10-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='state',
            field=models.CharField(choices=[('OKY', 'Good'), ('LST', 'Lost'), ('DMG', 'Damaged'), ('DST', 'Destroyed')], default='OKY', max_length=9),
        ),
    ]
