# Generated by Django 2.2.4 on 2019-10-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
