# Generated by Django 2.2.4 on 2019-09-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
        ('artefacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefact',
            name='belongs_to_families',
            field=models.ManyToManyField(related_name='has_artefacts', to='family.Family'),
        ),
    ]
