# Generated by Django 2.2.4 on 2019-09-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefact',
            name='test',
            field=models.TextField(default='0'),
        ),
    ]
