# Generated by Django 2.2.4 on 2019-10-07 04:10

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
        ('artefacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefact',
            name='belongs_to_families',
            field=models.ManyToManyField(related_name='has_artefacts', to='family.Family'),
        ),
        migrations.AddField(
            model_name='artefact',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={}, null=True),
        ),
    ]
