# Generated by Django 2.2.4 on 2019-09-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0002_auto_20190921_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='upload',
            field=models.FileField(blank=True, default=False, upload_to=''),
        ),
    ]
