# Generated by Django 2.2.4 on 2019-10-07 05:13

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0002_auto_20191007_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': [0, 0]}, null=True),
        ),
    ]
