# Generated by Django 2.2.4 on 2019-10-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0002_auto_20191015_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
