# Generated by Django 2.2.4 on 2019-09-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0002_artefact_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefact',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='test',
            field=models.TextField(default=''),
        ),
    ]
