# Generated by Django 2.2.4 on 2019-09-04 22:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0003_auto_20190905_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 9, 4, 22, 35, 3, 341826, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
