# Generated by Django 2.2.4 on 2019-09-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0004_auto_20190905_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefact',
            name='isDamaged',
            field=models.BooleanField(default=False),
        ),
    ]
