# Generated by Django 2.2.4 on 2019-10-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0004_auto_20191010_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='is_public',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
