# Generated by Django 2.2.4 on 2019-10-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0005_auto_20191010_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='is_public',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
