# Generated by Django 2.2.4 on 2019-09-04 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0005_artefact_isdamaged'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artefact',
            old_name='isDamaged',
            new_name='LostOrDamaged',
        ),
    ]
