# Generated by Django 2.2.4 on 2019-09-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0006_auto_20190905_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefact',
            name='isPublic',
            field=models.BooleanField(default=False),
        ),
    ]
