# Generated by Django 2.2.4 on 2019-09-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0007_artefact_ispublic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
