# Generated by Django 2.2.4 on 2019-10-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0008_auto_20191010_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefact',
            name='location_type',
            field=models.CharField(choices=[('place', 'place'), ('address', 'address')], default='address', max_length=9),
        ),
    ]
