# Generated by Django 2.2.4 on 2019-09-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0008_auto_20190905_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefact',
            name='artifact_flag_choices',
            field=models.CharField(choices=[('okay', 'No Problem'), ('lost', 'Lost'), ('damaged', 'Damaged'), ('destroyed', 'Destroyed')], default='okay', max_length=9),
        ),
    ]
