# Generated by Django 2.2.4 on 2019-10-11 02:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0009_artefact_location_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='is_public',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='location',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='location_type',
            field=models.CharField(blank=True, choices=[('place', 'place'), ('address', 'address')], default='address', max_length=9),
        ),
    ]
