# Generated by Django 2.2.4 on 2019-09-05 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0009_artefact_artifact_flag_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artefact',
            old_name='isPublic',
            new_name='is_public',
        ),
    ]
