# Generated by Django 2.2.4 on 2019-10-11 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0010_auto_20191011_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='belongs_to_families',
            field=models.ManyToManyField(null=True, related_name='has_artefacts', to='family.Family'),
        ),
    ]
