# Generated by Django 2.2.4 on 2019-09-05 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0010_auto_20190905_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artefact',
            old_name='test',
            new_name='information_on_handling',
        ),
        migrations.RemoveField(
            model_name='artefact',
            name='LostOrDamaged',
        ),
    ]
