# Generated by Django 2.2.4 on 2019-09-09 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artefacts', '0011_auto_20190905_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefact',
            name='artefact_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artefact_administrator_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
