# Generated by Django 2.2.4 on 2019-10-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0012_auto_20191011_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artefact',
            name='location_type',
        ),
        migrations.AlterField(
            model_name='artefact',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
