# Generated by Django 2.2.4 on 2019-09-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0013_auto_20190914_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefact',
            name='picture',
            field=models.URLField(default=False),
        ),
    ]
