# Generated by Django 2.2.4 on 2019-09-19 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0014_auto_20190919_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artefact',
            old_name='artefact_state',
            new_name='state',
        ),
    ]
