# Generated by Django 2.2.4 on 2019-09-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0014_artefact_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artefact',
            name='picture',
        ),
        migrations.AddField(
            model_name='artefact',
            name='upload',
            field=models.FileField(default=False, upload_to=''),
        ),
    ]
