# Generated by Django 2.2.4 on 2019-09-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0016_auto_20190916_1148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AddField(
            model_name='artefact',
            name='upload',
            field=models.FileField(default=False, upload_to=''),
        ),
    ]
