# Generated by Django 2.2.4 on 2019-09-18 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0017_auto_20190916_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artefact',
            name='information_on_handling',
        ),
    ]
