# Generated by Django 2.2.4 on 2019-09-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0018_remove_artefact_information_on_handling'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefact',
            name='information_on_handling',
            field=models.TextField(default=''),
        ),
    ]
