# Generated by Django 2.2.4 on 2019-09-19 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0005_auto_20190907_0308'),
        ('artefacts', '0019_artefact_information_on_handling'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefact',
            name='belong_to_family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='family.Family'),
        ),
    ]
