# Generated by Django 2.2.4 on 2019-09-19 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0020_artefact_belong_to_family'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artefact',
            name='information_on_handling',
        ),
    ]
