# Generated by Django 2.2.4 on 2019-09-20 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0021_remove_artefact_information_on_handling'),
        ('artefacts', '0014_auto_20190918_2105'),
    ]

    operations = [
    ]
