# Generated by Django 2.2.4 on 2019-09-26 12:49

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0022_merge_20190920_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefact',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={}, null=True),
        ),
    ]
