# Generated by Django 2.2.4 on 2019-09-28 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=150)),
                ('about', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('join_code', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('family_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administrator_of', to=settings.AUTH_USER_MODEL)),
                ('family_members', models.ManyToManyField(related_name='is_member_of', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'family',
                'verbose_name_plural': 'families',
                'ordering': ('-created_at',),
            },
        ),
    ]
