# Generated by Django 2.2.4 on 2019-09-04 07:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='join_code',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
