# Generated by Django 2.2.4 on 2019-09-07 02:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_auto_20190907_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='family_members',
            field=models.ManyToManyField(related_name='is_member_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
