# Generated by Django 2.2.4 on 2019-09-07 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0004_auto_20190907_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='family_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administrator_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
